---
- name: Test de connexion Jenkins vers Ansible
  hosts: all
  gather_facts: no  # On gagne du temps en ne récupérant pas toutes les infos du serveur
  
  tasks:
    - name: 1. Afficher un message dans la console Jenkins
      debug:
        msg: "Connexion SSH réussie avec le serveur 172.30.20.12 !"

    - name: 2. Créer un marqueur sur le serveur distant
      file:
        path: /tmp/vu_par_jenkins.txt
        state: touch
        mode: '0644'
